### ISSUE TITLE
parse_gitlog function not found

### ISSUE THREAD

**Issue by valentina-lenarduzzi** [sailuh/kaiaulu#125]
I have installed all the dependencies and I am running Kaiaulu (Social Smells Showcase vignette). I am first trying to run with one of the project already configured (Apr), but I always get the same error.

" Error in parse_gitlog(Perceval_path, git_repo_path): could not find function "parse_gitlog"

**Comment by carlosparadis** [comment]
@valentina-lenarduzzi thank you for posting it here. Have you tried to build the library from R studio? On a mac it is cmd + shift + b (#85). It should find the function after you load kaiaulu in the notebook. Please let me know if this works for you.

**Comment by valentina-lenarduzzi** [comment]
Solved, thank you.
