### ISSUE TITLE
object 'data.Author' not found

### ISSUE THREAD

**Issue by valentina-lenarduzzi** [sailuh/kaiaulu#127]
Hello, 
I am trying to run Kaiaulu, but I get stuck on data/author not found. 

Here is the error message when I execute the vignette git_log_showcase or social_smell_showcase. 

```
Warning in system2("git", args = c("--git-dir", git_repo_path, "log", flags,  :
  running command ''git' --git-dir ../git_repo/apr/.git log --raw --numstat --pretty=fuller --decorate=full --parents --reverse --topo-order -M -C -c > /tmp/gitlog.log 2>/dev/null' had status 128
Error in eval(bysub, x, parent.frame()) : object 'data.Author' not found
> 
```

**Comment by carlosparadis** [comment]
Hi,

Can you let me know if #108 solution works for you? It is likely you are not specifying correctly the data path. The error message may be misleading.

**Comment by carlosparadis** [comment]
I'm assuming this issue has been resolved. Please feel free to re-open otherwise.
