### ISSUE TITLE
Churn Observation - Social Smells Notebook

### ISSUE THREAD

**Issue by tuejari** [sailuh/kaiaulu#135]
I applied Kaiaulu, specifically the social smells notebook, to 23 different communities and for all of them the churn value returned 0. 
I have not looked into it in depth since I am specifically looking at the social smells results and not the churn metrics. However, I thought it was very odd that for 23 communities the churn value would all be 0, so there may be an issue in its implementation.

**Comment by carlosparadis** [comment]
@tuejari Posting here what we discussed via e-mail. You can safely ignore this post.

This is an error introduced when I renamed all columns in Kaiaulu all the way back in 0.0.9500 after my dissertation so it was more usable, the last change to this line was 16 months ago. The itm0 docs also had everything as 0s. 

Apparently asking R to subset a column that doesn't exist makes it return an empty table rather cause said column does not exist (hence resulting in churn 0).  Fixing the column names to the correct ones address the issue.
