### ISSUE TITLE
parse_gitlog throws "object 'data.Author' not found'

### ISSUE THREAD

**Issue by MahsaBazzaz** [sailuh/kaiaulu#139]
I am trying to run the social_smell_showcase, and I have only changed the path of Percival in the tools.yml as it is different from the default path:
> perceval: C:/Users/hmahs/anaconda3/Scripts/perceval

now when running the showcase I get this error:
> Warning in system2("git", args = c("--git-dir", git_repo_path, "log", flags,  :
  running command '"git" --git-dir ../rawdata/git_repo/helix/.git log --raw --numstat --pretty=fuller --decorate=full --parents --reverse --topo-order -M -C -c > /tmp/gitlog.log' had status 128

> Warning in system2(perceval_path, args = c("git", "--git-log", gitlog_path,  :
  running command '"C:/Users/hmahs/anaconda3/Scripts/perceval" git --git-log /tmp/gitlog.log ../rawdata/git_repo/helix/.git --json-line' had status 1

> Error in eval(bysub, x, parent.frame()) : object 'data.Author' not found

Can you me a hint on why this is happening?

**Comment by carlosparadis** [comment]
Hi Mahsa, 

I see a `C:` path. Are you trying to run on Windows? Currently, Kaiaulu will only work on Linux (tested on Ubuntu) or OS X. As far as I know Perceval by itself would not work on Windows either, which is required to use `parse_gitlog` from the social smells notebook. Normally the 'data.Author' issue is associated with #108.

**Comment by MahsaBazzaz** [comment]
That's right, I didn't see that in the documentation. Thank you very much!
