### ISSUE TITLE
CONTRIBUTING.md Resources Link no longer work

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#150]
@leilani-reich thanks for identifying this on #149 

Could you check if the links changed and if it is still possible to hyperlink to the new links? Otherwise, we can just try and specify more specifically the lesson and link the course instead.

**Comment by leilani-reich** [comment]
Hi Carlos, in regards to the link to the follow-up Udacity course you mention in CONTRIBUTING.md, which was called "GitHub & Collaboration" (by checking the link address), I noticed that this also links to the introductory git course "Version Control with Git" by Udacity. So I believe this follow-up course was removed or may have merged with the introductory git course. I was looking at a [previous article](https://www.udacity.com/blog/2017/05/job-skills-github-collaboration.html) on the course "GitHub & Collaboration" and within that article, if you click the link to the course, it also links back to "Version Control with Git."

In regards to the three links on "Create a Pull Request", "Stay in Sync with Code Repository", and "Commit Squash and Relabel", these all seem to be lessons associated with the "GitHub & Collaboration" course, which was taken down, which is likely why they all link back to the introductory git course, "Version Control with Git." Within this introductory git course, I didn't see any lessons on the above topics, so I don't think there is a way to link to them anymore. 

I found some other links related to the three lessons on git if that's helpful:
- Create a Pull Request - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
- Stay in Sync with Code Repository - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
- Commit Squash and Relabel - https://gist.github.com/lpranam/4ae996b0a4bc37448dc80356efbca7fa

Thanks,
Leilani

**Comment by carlosparadis** [comment]
Removing this from Milestone 1 and tagging as future until I find a better resource.

**Comment by carlosparadis** [comment]
For reasons unknown, I still have access to the course, but at the same time, it is no longer available. I've moved the associated section from Contributing.md with new working links directly to the videos to the Wiki: https://github.com/sailuh/kaiaulu/wiki/Learning-Resources 

It is less than ideal since the video covers only a small portion of the material (most are text and images), but it is still a very helpful resource due to the conceptual diagrams.  

I will close this issue once I commit changes removing the resources from CONTRIBUTING.md and pointing to the wiki.
