### ISSUE TITLE
Social Smell Kaiaulu Cheatsheet + Revision for Bugzilla

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#159]
[social-smells-cheatsheet.pdf](https://github.com/sailuh/kaiaulu/files/10833219/social-smells-cheatsheet.pdf)

> Hi Carlos, I've made a cheatsheet for social smells. I wasn't sure what folder to put it in, so I've uploaded it here.

_Originally posted by @leilani-reich in https://github.com/sailuh/kaiaulu/issues/151#issuecomment-1445289808_

**Comment by carlosparadis** [comment]
I split this into separate issues to make it easier to follow up. This looks great!

Here are some suggestions/follow-up:

0. Could you include Kaiaulu logo to the .pptx? It should be on the README
1. PDF here on the issue is fine. Could you also attach the .pptx next time?
2. *"The file ”tools.yml” must also be configured. See README for more information on downloading relevant packages:"* -> **"The file "tools.yml" must also be configured. See README for more information on 3rd party software dependencies."**
3. The pptx of datatable has a good example of how to add the copyright without taking so much space. Could you use their format?
4. "The social_smells_showcase.Rmd vignette introduces the main functionalities of Kaiaulu, including parsing and analyzing different types of software communication data to find social smells." -> **The social_smells_showcase.Rmd vignette introduces the social smell metrics of Kaiaulu, including git log and communication parsing and community detection algorithms.**
5. For the parse_gitlog and parse_mbox, note the information displayed includes real people's name. Could you also use icons as you did for identity matching? More specifically, the file icon with inside it saying .git and an arrow pointing to a table would suffice, and for mbox a .mbox file. Take a look on the data.table file for an example of compact table done in power point you could reuse. 
6. For identity match, the icons are fine, but if you could add .git and .mbox to the file icons, it would help emphasize the person icon is being now mapped on two different sources. 
7. For bipartite_graph_projection(), and to leverage the space obtained by the copyleft block, could you recreate this image on the ppt (instead of copy and paste) so it is editable on it too? 


![biparte_3](https://user-images.githubusercontent.com/17270563/221535441-92d6950e-af0f-4a0a-b560-b348f76bd534.png)

8. Instead of the functions of community_oslom() and recolor_network_by_community(), could you add the `filter_by_file_extension()` and `filter_by_filepath_substring()` (together)  before the mention of parse_gitlog()? This is a simple pair of functions, but they are more widely used everywhere than these last two, so I feel it would be more helpful. 

9. Given the suggestions for parse_mbox, I would extend them so instead of one file icon  with .mbox, you would have 3 file icons, with an arrow pointing to the table. The other two icons would contain Jira .json and GitHub.json. Additionally, beside parse_mbox(), you would also include parse_jira_replies() and parse_github_replies(). The explanation would remain simple:

"Parses an mbox, a file which stores emails in a mailbox. Returns a table with relevant fields for the mbox." -> **"Parses an mbox, a file which stores emails in a mailbox, and issue comments from JIRA and GitHub respectively if available. Returns a table of replies.**

10. Your last functions would be smell_organizational_silo(), smell_missing_links(), smell_sociotechnical_congruence() ... (the dot dot dot would be added to the .pptx too to suggest there are other functions). These are the functions that actually compute the social smell metrics. The following image remade on the .pptx should suffice (please replace the table with the one that already exists on pptx from data table package):


![table_4](https://user-images.githubusercontent.com/17270563/221538244-083310e0-7c34-44bb-8e60-0eb7fbb92fa8.png)

The final images of the network can be removed. They represent only 1 of the 3 metrics in visual form, so mentioning the metric functions would be more representative of the notebook.

Please let me know if anything is unclear. I will send the data.table pptx via e-mail to facilitate.

**Comment by leilani-reich** [comment]
Hi Carlos, I've made changes accordingly. How does this look?
[social-smells-cheatsheet.pptx](https://github.com/sailuh/kaiaulu/files/10848835/social-smells-cheatsheet.pptx)

**Comment by carlosparadis** [comment]
This looks great! 👍 

I think the only comment left which I overlooked on the last set of requests was:

Under identity match:

>  Finds all the identities representing the same individual for each user in the data in parse_gitlog and/or parse_mbox files. Returns a table with the different identity names matched to each user.

Change to:

> Finds all the identities representing the same individual for each user in the data in parse_gitlog, parse_mbox, parse_jira_replies, and/or parse_github_replies files. Returns a table with the different identity names matched to each user.

Accordingly, you should also add the associated JIRA and GitHub icons alongside the mbox icon towards the right.
-------------------

Note when we finish the Bugzilla milestone, we would be including here the parse_bugzilla too :)  

Please show the current version to @rnkazman for feedback today if possible.

**Comment by leilani-reich** [comment]
Thank you Carlos, I will keep that in mind.

**Comment by leilani-reich** [comment]
Hi Carlos, I added some new information for the identity_match() function according to the [itm0 documentation](http://itm0.shidler.hawaii.edu/kaiaulu/reference/identity_match.html) to be more precise. Also, I used tables for the gitlog, mbox, jira replies, and github replies since they are tables passed into identity_match() and not files. Let me know what you think.
[social-smells-cheatsheet.pptx](https://github.com/sailuh/kaiaulu/files/10859256/social-smells-cheatsheet.pptx)

**Comment by carlosparadis** [comment]
This looks perfect! I am leaving this issue open just so we remember to add the bugzilla function call once I get around reviewing your pull requests for Milestone 2.

**Comment by leilani-reich** [comment]
Hi Carlos, I added a small update with bugzilla functions. Although, I'm not sure whether I included them in the right places or if bugzilla should just be separate from things like identity_match(). Also, there is no bugzilla section to the config files so I added some parameters based on what I thought would be necessary. Should the bugzilla config be a separate issue as well? Please let me know what you think.

[social-smells-cheatsheet-bugzilla.pptx](https://github.com/sailuh/kaiaulu/files/11260557/social-smells-cheatsheet-bugzilla.pptx)

**Comment by carlosparadis** [comment]
Here's the promised review of this so you can update on your poster:

> Optional Fields

```yaml
issue_tracker:
jira:
  - domain
  - project_key
  - issues
  - issue_comments
github:
  - owner
  - repo
  - replies
bugzilla:
  - site_url
  - datetime
  - limit
  - replies
```

Let's go with the above for the Optional Fields (I am eliminating:  perc_issue_comments, perc_rest_issue_comments, restapi_issues, restapi_comments). Replies is a folder pointer to where all the various data for bugzilla will be downloaded, similar to GitHub. I will probably have to revisit this in the future, but for now let's err on being brief. As noted before, don't worry about integrating the conf file to the Notebook, i will do it down the road. This is just for the Cheat Sheet update.

> parse_mbox(), parse_jira_replies(), parse_github_replies(),
parse_bugzilla(), parse_bugzillarest(), parse_bugzilla_crawler_issue(), 
parse_bugzilla_crawler_comments()

Replace with:

parse_mbox(), parse_jira_replies(), parse_github_replies(),
parse_bugzilla_rest_comments()

Note: The additional functions for Bugzilla make it too cluttered. One function for each type of data should suffice. 

> Finds all the identities representing the same individual for each user in the data in the parse_gitlog, parse_mbox, parse_jira_replies, parse_github_replies, and/or any of the parsed bugzilla tables. Returns the list of tables, each with two added columns, `raw_name` and `identity_id`. `raw_name` contains all names matched to the user, while `identity_id` provides a unique identifier, starting at 1, for all names passed in across all list tables.

Replace with: 

Links users in the data (parse_gitlog, parse_mbox, parse_jira_replies, parse_github_replies, parse_bugzilla_rest_comments) by overlapping partial information. 

Note: Details of what it returns can be deferred to the function docs. 

> download_jira_data.Rmd
> download_github_comments.Rmd
> bugzilla_showcase.Rmd

Replace with: 


> download_mod_mbox.Rmd
> download_jira_data.Rmd
> download_github_comments.Rmd
> ~~bugzilla_showcase.Rmd~~ (We should rename this notebook to download_bugzilla.Rmd in the actual file too for consistency)
> social_smell_showcase.Rmd


Otherwise, I think this is enough. Reminder you have not added yourself yet on the Cheat Sheet above.

**Comment by leilani-reich** [comment]
Hi Carlos, the cheatsheet has been updated. I will update it on the kaiaulu_cheatsheet repo too.

[social-smells-cheatsheet-bugzilla.pptx](https://github.com/sailuh/kaiaulu/files/11331302/social-smells-cheatsheet-bugzilla.pptx)

**Comment by carlosparadis** [comment]
Hi Leilani,

The "note:" was meant as an FYI, no meant to be included on the PPT. Would you mind making one more commit to the other repo?

Also I missed this part:

> If you choose to do analysis on JIRA and/or GitHub replies data, you must run the following vignettes to download the data first:

Replace with:

If you choose to do analysis on JIRA and/or communication data, you must run the following vignettes to download the data first:

----

Sorry for the confusion.

**Comment by leilani-reich** [comment]
since there is download_bugzilla.Rmd, shouldn't I say "If you choose to do analysis on JIRA, Bugzilla, and/or communication data, you must run the following vignettes to download the data first:"?

**Comment by carlosparadis** [comment]
Hi, just to be clear:

The note I was referring to remove was: 

> Note: Details of what it returns can be deferred to the function docs. 

As for your question: 

>  since there is download_bugzilla.Rmd, shouldn't I say "If you choose to do analysis on JIRA, Bugzilla, and/or communication data, you must run the following vignettes to download the data first:"?

I think what I am trying to do is find a more general sentence. You see, all the download notebooks you mentioned constitute communication data that should be integrated into the communication graph. This is why I didn't want to emphasize just JIRA, or Bugzilla, because Mailing Lists, GitHub Issues & Pull Requests comments are one and the same. And virtually anything else one may be using to talk. 

How about:

`If you choose to do Social Smell analysis, you must run the following vignettes to download the necessary communication data first depending on what the project uses:`

Or something equivalent?

**Comment by leilani-reich** [comment]
I've updated the files and made a new commit.
I will post here as well.

[social-smells-cheatsheet.pdf](https://github.com/sailuh/kaiaulu/files/11342122/social-smells-cheatsheet.pdf)
[social-smells-cheatsheet.pptx](https://github.com/sailuh/kaiaulu/files/11342123/social-smells-cheatsheet.pptx)
