### ISSUE TITLE
Confusion in Installation Documentation

### ISSUE THREAD

**Issue by lh-zhan** [sailuh/kaiaulu#180]
Hi there!

When I tried to follow the installation documentation, under https://github.com/sailuh/kaiaulu#gitlog-analysis

I'm not sure what does the `viz on gitlog analysis.` refer to for the fourth point, same goes to 
https://github.com/sailuh/kaiaulu#mailing-list-analysis  and
https://github.com/sailuh/kaiaulu#dependency-analysis

It would be great if that can be expanded :)

Thanks!

**Comment by carlosparadis** [comment]
The README was modified and should no longer mention `viz`. I am not sure what the other hyperlinks are and searching for the keyword on the repo only returns one specific mention in the source code. Feel free to re-open if it is still present somewhere I missed.
