### ISSUE TITLE
DV8 filenames mismatch with Perceval

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#183]
Refer to https://github.com/sailuh/kaiaulu/pull/171#issuecomment-1501706352

**Comment by carlosparadis** [comment]
I am confused with this issue. Is this a duplicate of #172? Or #184?

**Comment by leilani-reich** [comment]
Hi Carlos,
yes I think this #183 and #184 are referring to the same thing. I can delete this issue.

**Comment by carlosparadis** [comment]
No worries, lets just mark it as duplicate on the label and close!
