### ISSUE TITLE
parse_mbox can't parse .mbox files when less fields are available in the data

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#185]
```
Hi @carlosparadis ! I've followed all of the instructions related to this issue, made sure I have the 0.12.24 version, tested out perceval from the vignettes/ directory and it works just fine. 

The comment that I used to test out `@mac-groundapple vignettes % /Users/Desktop/kaiaulu/env/bin/perceval mbox dev_helix_apache_org ../../rawdata/mbox/dev_helix_apache_org.mbox ` 
It ran without any error and gave me the desired result. I also made sure my perceval path specified in tool.yml aligns with the perceval path that I used above

However, when I try to execute the .Rmd file, I got `Error in data.table::setnames(perceval_parsed, c("data.Date", "data.To",  : 
  Items of 'old' not found in column names: [data.Cc, data.In.Reply.To]. Consider skip_absent=TRUE.`

My set up in helix.yml is
`  mbox: ../../rawdata/mbox/dev_helix_apache_org.mbox
   domain: http://mail-archives.apache.org/mod_mbox
   list_key:
     - dev_helix_apache_org`
 
I'm running the .rmd file inside of Rstudio.
My file structure looks like this:
/Desktop/kaiaulu/vignettes
/Desktop/rawdata/mbox/dev_helix_apache_org.mbox

Any help is appreciated!
```

_Originally posted by @lh-zhan in https://github.com/sailuh/kaiaulu/issues/145#issuecomment-1500763100_

It seems my first guess was the problem after all. The original implementation of parse_mbox() was done using only OpenSSL as input, and I incorrectly assumed at the time the mbox files had a consistent number of fields (which would result in a consistent number of columns). 

I was wrong. 

The error above occurs due to the mbox archive in question lacking the specified fields. I have fixed this, so the code does not assume all fields are always present. This means the number of columns available resulting from parse_mbox() will differ from project to project, but I guess it is better than filling several columns with NA.

**Comment by lh-zhan** [comment]
Hi @carlosparadis 

Thanks for putting in a fix for the issue! Sadly, after pulling the latest change and rerun the social_smell notebook using the helix.yml and rawdata, I got:

```
Error in data.table::setnames(perceval_parsed, c("data.Date", "data.To",  : 
  Items of 'old' not found in column names: [data.Cc]. Consider skip_absent=TRUE.
```

I reran the same notebook but swapped helix.yml with thrift.yml and it worked. 

The mbox that I used: https://lists.apache.org/list?dev@helix.apache.org:2023-1
I also tried running perceval in terminal using this mbox, and it worked well without any error.

**Comment by lh-zhan** [comment]
My apologies for not building after pulling the changes and cause of confusion! Totally my fault due to my unfamiliarity with R. After building the latest change, it ran without any error. 

Thank you for following through this issue and putting in a fix!!

**Comment by carlosparadis** [comment]
No problem! Thank you for finding and working with me to solve the bug :)
