### ISSUE TITLE
DV8 End-to-end testing

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#186]
We will add unit tests for non-wrapper functions of DV8. This includes dependencies_to_sdsmj(), gitlog_to_sdsmj(), parse_dv8_metrics_decoupling_level(), parse_dv8_architectural_flaws(), and parse_dv8_clusters(). We will not be testing the wrapper functions.

Please let me know if I missed any functions.

![dv8_kaiaulu_api_v3_task_assignments](https://user-images.githubusercontent.com/17270563/226171262-03867e91-4fa1-42db-ae4d-1598b6dd09d7.png)

**Comment by carlosparadis** [comment]
For the record, this task is being pushed to the lowest priority given the various other tasks still pending that need to be addressed.
