### ISSUE TITLE
Kaiaulu Story Poster

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#187]
To discuss the content of the final poster for the Software Analytics Insights team. This poster is due 4/28 at 11:55pm. 
ICS Project Day will be 5/4 12:00pm-3:00pm Campus Center, CC 307/308/309/310.

Outline (in-progress):
- What is the story?
  - Kaiaulu - What is Kaiaulu’s motivation? Capability for analyzing software projects
  - Kaiaulu’s capabilities and what was lacking
  - Project Statement - Filling the gap
- Talk about the pieces we added using the cheatsheets as visuals
- Conclusion
  -  We can do this type of analysis, it has value for project managers

**Comment by carlosparadis** [comment]
For the record, this was PR'ed and merged to: https://github.com/sailuh/kaiaulu_cheatsheet
