### ISSUE TITLE
Final Presentation for Software Analytics Insights team

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#188]
We will iterate on our work for our capstone project final presentation for Kaiaulu due 4/25.
The main focus of the presentation will be DV8 integration, but we can also discuss milestones 1 & 2.

**Comment by carlosparadis** [comment]
For the record, this was PR'ed and merged in the other repo: https://github.com/sailuh/kaiaulu_cheatsheet/issues/3
