### ISSUE TITLE
Bugzilla Showcase Notebook

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#199]
@malialiu @leilani-reich 

I am creating this separate issue to tie your Bugzilla Notebook PR since the original at 152 didn't make much sense to me. 

@leilani-reich I know you verified with me the 3 asks from the long 3-hour call for Malia to implement. Could you link the comment here? I can't find it.

@malialiu Could you confirm you have done them too and where in the Notebook? I will go ahead and accept the PR but I wanted to check this here too.

**Comment by carlosparadis** [comment]
Also referencing the issue comparison spreadsheet here: https://github.com/sailuh/kaiaulu/pull/164#issuecomment-1529195613

**Comment by malialiu** [comment]
https://github.com/sailuh/kaiaulu/pull/164#issuecomment-1514345062 This is the 3 asks.

**Comment by carlosparadis** [comment]
Noting here the reference to the final specification of the Bugzilla API: https://github.com/sailuh/kaiaulu/pull/155#issuecomment-1519036410 

In the future, I will likely be more careful with the discussion separation to facilitate finding things. We certainly generated a lot of discussions!

@malialiu So, did you check for the 3 asks? Are they in the notebook too?

**Comment by malialiu** [comment]
Yes, they in the notebook. Let me know if I missed anything.

**Comment by malialiu** [comment]
> Also referencing the issue comparison spreadsheet here: [#164 (comment)](https://github.com/sailuh/kaiaulu/pull/164#issuecomment-1529195613)

Sorry I sent the wrong one previously, attached is the updated one.
[Bugzilla Checks (1).xlsx](https://github.com/sailuh/kaiaulu/files/11362910/Bugzilla.Checks.1.xlsx)

**Comment by carlosparadis** [comment]
This task was completed. Forgot to close the issue :)
