### ISSUE TITLE
User Experience Report

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#225]
Several artifacts together compose the documentation of Kaiaulu: 

1. **README.md**
2. CONTRIBUTING.md 
3. Config files (be them either the /conf or tools.yml)
4. The Wiki 
5. The Kaiaulu major use cases 
6. **The notebooks** 
7. **The documentation on each function in R/ (e.g. when you type `?parse_gitlog`). 
8. **pkgdown docs**: i.e. http://itm0.shidler.hawaii.edu/kaiaulu 
9. The tags on GitHub used to annotate the issues, and the template of issues themselves (which is currently none)
10. Publications about Kaiaulu
11. The man page of Kaiaulu CLI, which is the server-side endpoint of Kaiaulu (https://github.com/sailuh/kaiaulu/tree/master/exec) 

## Task 

Task: For this deliverable, I would like you to download and open Kaiaulu in dev mode on RStudio, and execute the Notebook http://itm0.shidler.hawaii.edu/kaiaulu/articles/download_jira_data.html. You should be able to "knit" the Notebook entirely, obtaining files for an open source project. The current project configuration file should suffice.  

## User Experience Report 

The User Experience report should be done independently, therefore one User Experience report for each of you. You should defer comparing notes until and during the meeting, so to avoid mixing or missing points of confusion. 

The User Experience Report **should be a bullet list**. Each bullet is a difficulty or confusion you encounter when trying to accomplish the task. This may involve one documentation file, or multiple files. This may be a passage of the documentation that is confusing, or the inability to find the information (please note what) you need to proceed on the task. For difficulties encountered that refer to specific parts of the Notebook, you should also include the line of the file using GitHub embedded links. For example, if you can click the line number of the Notebook, hold shift on your keyboard, select another line number and click "Copy permanent link" to do the following:

https://github.com/sailuh/kaiaulu/blob/6ff61e558cb2b2a658dc90c93649d41ab3f30022/vignettes/download_jira_data.Rmd#L31-L34

This makes it very clear the passage you are referring to. You can do the same for anything in the repo. 

For example of bullet: Basically, you can perform the task above, and as you find points of confusion or difficulty, please note them down using as reference the artifacts enumerated above. For example, "I was unable to run this code block despite looking at Docs X file Y and Z because..". Or if you have a suggestion of improvement, please also note down in your report. Situations where you look in a file hoping to find information and you do not are also helpful. This means the docs should be moved across different files. 

In short, it is important it is clear the artifact that causes confusion, and what the confusion is at least. Suggestions on how to improve are also welcomed, but we can iterate. Please be detailed in the report. 

## Questions

If you are unclear how to proceed with the task, please post questions on Discussions in addition to writing the bullet: https://github.com/sailuh/kaiaulu/discussions since they are easier to reply than issues. In the process of asking questions, you will inevitably read the title of each other questions. If you share a question or difficulty the other has, please use the upvote function to indicate that and iterate with me on the same question until it is resolved. Otherwise, please avoid looking further until we are done with the reports. Lastly, please don't create issues for questions (later on when development starts this will change, but not for now). If your question is specifically about the User Experience Report, then it is ok to reply in this issue. 

I expect some terms in the Task may not make sense due to lack of background in R development. Maybe some of the documentation files mentioned will not even be clear where they are or what they are! That is fine! Please add a bullet to your User Experience Report, and if you are unable to figure out, post a question on Discussions. As you can imagine, your reports are likely to end up lengthy! But this in turn makes it more clear more documentation may be needed, or resources to R and R development in general too.

## Deadline (Next Friday ; Sep, 8) 

Let's target having the User Experience Report for this Friday next week posted to this issue for each of you (again, please avoid reading each other's until the meeting even after posted here). Try to ask as you go, rather than post 30 questions at the last minute. It is ok if the task is not yet complete at that point, but I am hopeful we should have a sufficient amount of questions and early experience report by then from trying to install and/or running the Notebook. 

Thanks!

**Comment by Rubegen** [comment]
User Experience Report:

-Trouble Installing Perceval. Some tests were failing because perceval package was not detected. Later found out that perceval is not necessary for our task.

-Had problems downloading JirAgileR package but quickly resolved it by reading further into the documentation and seeing the solution

-Running commands in R console starts you off at a closer directory than if you were to run from Terminal

-Download Jira Comments notebook run issues: not able to find Kaiulu/kaiulu/rawdata/issue-tracker directory and therefore not able to write to it. We fixed this in our meeting and I learned that this was not an existing directory, but rather one that we need to manually create in order to write to it.


-Some issues with mbox package. Tests not detecting mbox and therefore failing

-Download_jira_data.rmd file for running that notebook was failing because there were multiple instances of the code where it was manually set to FALSE so as not to allow any data downloading. Was confused why the notebook would not run properly and it was because we needed to read the code and understand what those errors were being caused by and easily switch it off.

**Comment by waylonho** [comment]
User Experience Report

- had trouble installing devtools package, had to install other packages first. After multiple tries devtools eventually installed successfully. Searched kaiaulu README for explanation but it only says "run the unit tests". Online documentation of devtools was not very helpful.

- running devtools::test() - 9 failed, 42 pass. Unsure about why some failed but rest of installation worked fine.

- trouble installing JirAgileR package, said that version of R was incompatible. Read CRAN documentation and ended up successfully installing it.

- require(kaiaulu) gave error that library didn't exist. Was initially confused but then realized it was a new session that didn't save and built kaiaulu again before executing notebook. Suggestion: mention building kaiaulu first in download_jira_data notebook, silly unknown mistake but quickly resolved.

- issue with line 90: jsonlite::write_json(json_issues,save_path_issue_tracker_issues). Couldn't find rawdata and issue_tracker folders. Seemed to indicate file path issue. In meeting, created the directories and proper file structure.

- lines in download_jira_data.Rmd had eval = FALSE (lines 52, 72, 108). Had to remove these.

- same as 5th bullet for line 90 where couldn't find geronimo_issues.json, even after fixing file path and eval. Not sure but it seems like geronimo_issues.json is not downloading to the folder. Other chunks execute fine until here.
