### ISSUE TITLE
Parallel git log entity analysis

### ISSUE THREAD

**Issue by nicolehoess** [sailuh/kaiaulu#231]
For evolutionary analyses, the git history may be analyzed over several time windows. To speed up such analyses, I would like to propose a parallel version of the git log entity analysis notebook in `vignettes/gitlog_entity_parallel_showcase.Rmd`, which uses the Apache Spark git project configured in `conf/spark.yml` for demonstration purposes. 

The notebook depends on the R `doParallel` and `doSNOW` packages to parallelize the iteration over multiple time windows in `foreach`-loops.

Note: Both R packages work for Unix-like systems only. So far, the notebook has been tested on machines with up to 16 cores.

**Comment by carlosparadis** [comment]
Thank you @nicolehoess! Please feel free to PR the code and I can offer more feedback :)
