### ISSUE TITLE
Create a fake data generator for mbox

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#238]
The goal of this issue is to do something similar to:

https://github.com/lfd/codeface/blob/e6640c931f76e82719982318a5cd6facf1f3df48/codeface/test/integration/gitproject.py#L213-L242

So we can create fake mbox files. You can refer to the example above, which was explained before on #227, but you should not use the example in your code. Instead, use the Perceval you installed use one Kaiaulu Mailing List Downloaders to download some .mbox data and use that as example.

Please anonymize information that is not parameterized (see codeface replaced with "example"). 

Note you will also need to write the example functions, and subsequently call `parse_mbox` on them, much like #227

**Comment by Rubegen** [comment]
Hi Carlos, just a few questions about this deliverable. Just to clarify I am creating a method that allows us to create fake mbox files. I am using the download_mod_mbox function in download.R  to download data and use that as the basis for my method. I ran 
`> download_mod_mbox("https://lists.apache.org/list.html?dev@camel.apache.org", "apr-dev", 2022, 2023, "/Users/rubenjacobo/downloads/example_mod_data")
[1] "/Users/rubenjacobo/downloads/example_mod_data"` on the R Console and I think I was able to download an mbox file into my downloads. 
Now I need to create a method similar to the one you showed from codeface but make sure the data is anonymized and replaced by example. Please correct me if I am mistaken on any part above. 
Where in the project should this method be placed?

**Comment by carlosparadis** [comment]
Yes, your understand is correct! You should have obtained a few files like 202301.mbox. This is your example dataset. You can open them with a text editor to inspect too. 

The function should go on a file called mail.R. If it doesn't exist, you can create one, and attach the LICENSE information you see on the top of other files. 

I suggest you think a bit about what functions we should have, and post here on the issue as checkboxes so we can have the forest for the tree. For instance, how about writing the function name and parameters and how you plan to write it? That way rather than wait until you finish the code for me to validate the concept, you get that even before you start. 

You can use that format I did for the git log for example. Start from the mail.R interface, then the example.R, then the unit tests as checkboxes separated in 3 steps.

**Comment by Rubegen** [comment]
### Step 1:
-Create a function that allows us to make fake mbox data inside mail.R file

### Step 2:
- Write an example function, similar to what we did on issue 227  that uses the function we made in step 1 to create multiple examples of fake mbox data to ensure that step 1 is fully functional. These methods will be written in example.R
**Not sure exactly what examples I am going to make

### Step 3:
- Create unit tests to test the example functions that I made in example.R. We will create a new file in the test folder called test-mail.R

**Comment by carlosparadis** [comment]
@Rubegen I missed this since I think you made a post earlier with a draft and updated after (edits will not generate e-mail notifications for me, so it is a good idea to ping when ready to discuss if doing edits).

All your understanding is correct. I'd say your next step is to refine them while working on the code. I'd recommend post them and pinging me while coding so I an get back to you at the earliest. But don't block waiting on me, keep going on the code. I think you fully understand what this task is for, so it is just a matter of thinking what unit tests makes sense.

**Comment by Rubegen** [comment]
The examples I am planning to add to example.R are:
- An example mbox with all parameters filled in
- An example mbox that has randomize_email_case=False which means that the subject and content of the email will not be randomized/hidden
-An example mbox with a date and time that hasn't occured yet. For example an mbox set on (04/25/2025)

**Comment by carlosparadis** [comment]
- Your first unit test, to check all parameters are parsed correctly, is on point. The function I use to parse data should, well, parse data I care about. So doing expect_equal on the raw data fields to the parsed data is good. Considering Perceval is the one doing that, you are really asking if Perceval can properly parse an mbox file and give us data we need for the rest in Kaiaulu. This also guarantees that if should we ever replace Perceval for another parser, then parse_mbox should still guarantee these data fields are there, which is very important.  

- Your second unit test is not wrong, but it is less interesting for the parse_mbox: The function is not supposed to verify if an e-mail came from the future, so unit testing it for that doesn't tell me much. A more interesting unit test here is the reverse of your first case: What happens if there is missing data? For example, the timestamp, or the header, or the sender. This is more likely to happen, and I don't know if Perceval will break. In a project I analyzed, the sender data went missing from older entries. I imagine the mail client at the time may have gotten corrupted. 

- Your third test is...strange. I am not sure what this randomize parameter does (and frankly I would not include this in the function, the randomizer would be an external function calling this one). Regardless, observe if you are unit testing the randomizer, then you are unit testing your fake data generator. You should be unit testing parse_mbox instead (!) So what else can you unit test? I believe checking parse_mbox() is capturing timezone information is a good idea on its own unit test. If we in the future choose another tool other than Perceval, we want to make sure it also can parse said information.

Let me know if you can think of any other.

**Comment by Rubegen** [comment]
Hi Carlos, thank you for the feedback. Given the approaching deadline, I will focus all my attention on the first option (the one that you cleared) and write the associated unit test. If time permits I will ping you and try to squeeze in more examples and tests. LMK if this is okay. Thanks

**Comment by carlosparadis** [comment]
Yes, this is fine and very reasonable. I'd rather you have one unit test and the whole thing flashed out than everything half-done. Good call.
