### ISSUE TITLE
Cheat Sheet for Refreshers

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#294]
Here are the 3 major points that should be covered in this data cheet: 

 * Standardization of the Downloaders file naming 
 * Refreshers capitalizing on said standardization to update data
 * /exec scripts that give access to the function to put on a cron job for ongoing project monitoring

Reminder this basically is work towards your poster: Prior groups just included this as the center piece of the poster. You are more than welcome to make a few sketches on paintbrush and paste to this issue to save time before spending time on the actual .pptx. 

Please do refer to the existing Cheat Sheets in Kaiaulu to get a sense on how content is presented. I'd in fact recommend you start an existing one and just edit as needed. The Fake Data Generator Cheat Sheet which can only be found on the repo is likely to offer a good set of starting icons to use.

**Comment by Ssunoo2** [comment]
* [Cheat sheet guide: ](https://github.com/rstudio/cheatsheets/tree/main)
* [Kaiaulu cheat sheet repositories: ](https://github.com/sailuh/kaiaulu_cheatsheet/tree/main)

**Comment by Ssunoo2** [comment]
first concept design thanks to @anthonyjlau :
![cheatsheet_template](https://github.com/sailuh/kaiaulu/assets/97641529/a90de03b-eaa0-4973-88b1-84579c6df808)
We should also include the QR code to the repo: 
![287413897-b38e632e-ff91-47a7-a06b-d13e2fa1023a](https://github.com/sailuh/kaiaulu/assets/97641529/9b0a3d39-876c-4a1b-a4f0-4358668011a9)

**Comment by carlosparadis** [comment]
Thanks for remembering the QR code!

**Comment by carlosparadis** [comment]
<img width="721" alt="Screen Shot 2024-04-28 at 2 48 20 AM" src="https://github.com/sailuh/kaiaulu/assets/17270563/02671137-8c19-41f8-a0bb-e327f7c3bcd6">


The Cheatsheet for the Refresher is done, so I will close this issue.
