### ISSUE TITLE
Improve README First Setup.

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/kaiaulu#85]
@harismumtaz18 pointed out a missing step on the README. 

When first opening the project in dev mode on a new computer, one must also build it for the first time on the top-right pane of RStudio, selecting the tab `Build` and then the button `Install and Restart`. 

Will add to the README soon after I get a chance. Feel free to post anything else here that could use a brush up too or via Skype as usual and I will add a note on this or a separate issue depending on what it is :) 

Thanks!

**Comment by ronenlh** [comment]
This doesn't work for me, it get the error:

```
==> R CMD INSTALL --no-multiarch --with-keep.source kaiaulu

* installing to library ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library’
ERROR: dependencies ‘httr’, ‘curl’, ‘gh’, ‘XML’, ‘RColorBrewer’, ‘docopt’ are not available for package ‘kaiaulu’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/kaiaulu’

Exited with status 1.
```

**Comment by ronenlh** [comment]
Solved by installing each package in the console, e.g:
```
install.packages("docopt")
```

**Comment by carlosparadis** [comment]
Thanks, I guess currently you do have to install it manually. Once I version the fixes on the package checks, this should go away and the following command should work:

`devtools::install_github("sailuh/kaiaulu")`

However, that will not install the third party dependencies certain functions require (you will know it from the function signature, as it will require the third party tool bin path to be passed directly or via `tools.yml`.

**Comment by carlosparadis** [comment]
I noticed on the above R 4.1 was being used. Kaiaulu is still being tested on version 3.6. I will remember this when I test version 4.1 again. Since others could install on 3.6 with current settings, and README has since been heavily updated, I am closing this.
